simple_model:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 20

    # Velocity Controllers ---------------------------------------
  base_to_wheel1_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: base_to_wheel1_joint
    pid: {p: 1.0, i: 1.0, d: 0.0}
  base_to_wheel2_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: base_to_wheel2_joint
    pid: {p: 1.0, i: 1.0, d: 0.0}
  base_to_wheel3_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: base_to_wheel3_joint
    pid: {p: 1.0, i: 1.0, d: 0.0}
  base_to_wheel4_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: base_to_wheel4_joint
    pid: {p: 1.0, i: 1.0, d: 0.0}
